import type { Config } from "tailwindcss";

export default {
    content: [
        "./app/**/*.{js,ts,jsx,tsx}",
        "./components/**/*.{js,ts,jsx,tsx}",
        "./lib/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                ink: {
                    950: "var(--ink-950)",
                    900: "var(--ink-900)",
                    800: "var(--ink-800)",
                    700: "var(--ink-700)",
                    600: "var(--ink-600)",
                    500: "var(--ink-500)",
                },
                paper: {
                    50: "var(--paper-50)",
                    100: "var(--paper-100)",
                    200: "var(--paper-200)",
                    300: "var(--paper-300)",
                },
                brass: {
                    50: "var(--brass-50)",
                    100: "var(--brass-100)",
                    200: "var(--brass-200)",
                    300: "var(--brass-300)",
                    400: "var(--brass-400)",
                    500: "var(--brass-500)",
                    600: "var(--brass-600)",
                    700: "var(--brass-700)",
                },
                sage: {
                    50: "var(--sage-50)",
                    100: "var(--sage-100)",
                    300: "var(--sage-300)",
                    500: "var(--sage-500)",
                    600: "var(--sage-600)",
                    700: "var(--sage-700)",
                },
                coral: {
                    50: "var(--coral-50)",
                    100: "var(--coral-100)",
                    300: "var(--coral-300)",
                    500: "var(--coral-500)",
                    600: "var(--coral-600)",
                    700: "var(--coral-700)",
                },
                slate: {
                    50: "var(--slate-50)",
                    100: "var(--slate-100)",
                    200: "var(--slate-200)",
                    300: "var(--slate-300)",
                    400: "var(--slate-400)",
                    500: "var(--slate-500)",
                    600: "var(--slate-600)",
                    700: "var(--slate-700)",
                    800: "var(--slate-800)",
                    900: "var(--slate-900)",
                },
            },
            fontFamily: {
                sans: "var(--font-sans, system-ui)",
                display: "var(--font-display, serif)",
                mono: "var(--font-mono, monospace)",
            },
            spacing: {
                0: "var(--space-0, 0)",
                1: "var(--space-1, 4px)",
                2: "var(--space-2, 8px)",
                3: "var(--space-3, 12px)",
                4: "var(--space-4, 16px)",
                5: "var(--space-5, 20px)",
                6: "var(--space-6, 24px)",
                8: "var(--space-8, 32px)",
                10: "var(--space-10, 40px)",
                12: "var(--space-12, 48px)",
                16: "var(--space-16, 64px)",
                20: "var(--space-20, 80px)",
            },
            borderRadius: {
                xs: "var(--radius-xs, 4px)",
                sm: "var(--radius-sm, 6px)",
                md: "var(--radius-md, 10px)",
                lg: "var(--radius-lg, 14px)",
                xl: "var(--radius-xl, 20px)",
                pill: "var(--radius-pill, 999px)",
            },
            boxShadow: {
                0: "var(--elev-0, none)",
                1: "var(--elev-1)",
                2: "var(--elev-2)",
                3: "var(--elev-3)",
                4: "var(--elev-4)",
            },
        },
    },
    plugins: [],
} satisfies Config;
