create table if not exists public.cliente (
  id bigint generated by default as identity primary key,
  nombre varchar(160) not null,
  telefono varchar(40),
  nombre_normalizado varchar(160) not null unique,
  estado varchar(16) not null default 'activo',
  creado_en timestamptz not null default now(),
  modificado_en timestamptz not null default now()
);

create table if not exists public.medio_pago (
  id bigint generated by default as identity primary key,
  codigo varchar(50) not null unique,
  nombre varchar(120) not null unique,
  activo boolean not null default true,
  creado_en timestamptz not null default now(),
  modificado_en timestamptz not null default now()
);

create table if not exists public.venta (
  id bigint generated by default as identity primary key,
  empresa varchar(32) not null,
  tipo varchar(16) not null,
  numero_referencia varchar(100) not null,
  codigo_venta varchar(9),
  descripcion text not null,
  fecha_venta date not null,
  valor_total numeric(12,2) not null,
  cliente_id bigint references public.cliente(id),
  estado varchar(16) not null default 'activo',
  creado_en timestamptz not null default now(),
  modificado_en timestamptz not null default now(),
  constraint venta_valor_total_non_zero check (valor_total <> 0)
);

create table if not exists public.pago (
  id bigint generated by default as identity primary key,
  venta_id bigint not null references public.venta(id) on delete cascade,
  medio varchar(60) not null,
  monto numeric(12,2) not null,
  constraint pago_monto_non_zero check (monto <> 0)
);

create table if not exists public.admin_user (
  id bigint generated by default as identity primary key,
  username varchar(80) not null unique,
  password_hash varchar(255) not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_cliente_nombre_normalizado on public.cliente(nombre_normalizado);
create index if not exists idx_venta_fecha_venta on public.venta(fecha_venta);
create index if not exists idx_pago_venta_id on public.pago(venta_id);

alter table public.cliente enable row level security;
alter table public.medio_pago enable row level security;
alter table public.venta enable row level security;
alter table public.pago enable row level security;
alter table public.admin_user enable row level security;
