/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,ts,jsx,tsx}", "./components/**/*.{js,ts,jsx,tsx}", "./lib/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        /* Core palette */
        ink: {
          950: "var(--ink-950)",
          900: "var(--ink-900)",
          800: "var(--ink-800)",
          700: "var(--ink-700)",
          600: "var(--ink-600)",
          500: "var(--ink-500)",
        },
        paper: {
          50: "var(--paper-50)",
          100: "var(--paper-100)",
          200: "var(--paper-200)",
          300: "var(--paper-300)",
        },
        brass: {
          50: "var(--brass-50)",
          100: "var(--brass-100)",
          200: "var(--brass-200)",
          300: "var(--brass-300)",
          400: "var(--brass-400)",
          500: "var(--brass-500)",
          600: "var(--brass-600)",
          700: "var(--brass-700)",
        },
        sage: {
          50: "var(--sage-50)",
          100: "var(--sage-100)",
          300: "var(--sage-300)",
          500: "var(--sage-500)",
          600: "var(--sage-600)",
          700: "var(--sage-700)",
        },
        coral: {
          50: "var(--coral-50)",
          100: "var(--coral-100)",
          300: "var(--coral-300)",
          500: "var(--coral-500)",
          600: "var(--coral-600)",
          700: "var(--coral-700)",
        },
        slate: {
          50: "var(--slate-50)",
          100: "var(--slate-100)",
          200: "var(--slate-200)",
          300: "var(--slate-300)",
          400: "var(--slate-400)",
          500: "var(--slate-500)",
          600: "var(--slate-600)",
          700: "var(--slate-700)",
          800: "var(--slate-800)",
          900: "var(--slate-900)",
        },
        /* Semantic surfaces */
        surface: {
          app: "var(--surface-app)",
          panel: "var(--surface-panel)",
          "panel-alt": "var(--surface-panel-alt)",
          sunken: "var(--surface-sunken)",
          inverse: "var(--surface-inverse)",
        },
      },
      fontFamily: {
        sans: "var(--font-sans)",
        display: "var(--font-display)",
        mono: "var(--font-mono)",
      },
      spacing: {
        0: "var(--space-0)",
        1: "var(--space-1)",
        2: "var(--space-2)",
        3: "var(--space-3)",
        4: "var(--space-4)",
        5: "var(--space-5)",
        6: "var(--space-6)",
        8: "var(--space-8)",
        10: "var(--space-10)",
        12: "var(--space-12)",
        16: "var(--space-16)",
        20: "var(--space-20)",
      },
      borderRadius: {
        xs: "var(--radius-xs)",
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        pill: "var(--radius-pill)",
      },
      boxShadow: {
        0: "var(--elev-0)",
        1: "var(--elev-1)",
        2: "var(--elev-2)",
        3: "var(--elev-3)",
        4: "var(--elev-4)",
      },
      fontSize: {
        "display-xl": ["var(--fs-display-xl)", { lineHeight: "var(--lh-tight)" }],
        "display-lg": ["var(--fs-display-lg)", { lineHeight: "var(--lh-tight)" }],
        "display-md": ["var(--fs-display-md)", { lineHeight: "var(--lh-tight)" }],
        "h1": ["var(--fs-h1)", { lineHeight: "var(--lh-snug)" }],
        "h2": ["var(--fs-h2)", { lineHeight: "var(--lh-snug)" }],
        "h3": ["var(--fs-h3)", { lineHeight: "var(--lh-snug)" }],
        "h4": ["var(--fs-h4)", { lineHeight: "var(--lh-snug)" }],
        "body": ["var(--fs-body)", { lineHeight: "var(--lh-normal)" }],
        "body-sm": ["var(--fs-body-sm)", { lineHeight: "var(--lh-normal)" }],
        "caption": ["var(--fs-caption)", { lineHeight: "var(--lh-normal)" }],
        "overline": ["var(--fs-overline)", { lineHeight: "var(--lh-normal)" }],
      },
      transitionDuration: {
        1: "var(--dur-1)",
        2: "var(--dur-2)",
        3: "var(--dur-3)",
      },
    },
  },
  plugins: [],
};
